### ISSUE TITLE
"font.vbs" cannot be added to the installation package

### ISSUE THREAD

**Issue by ZhkAff** [oldj/node-font-list#1]
When I packaged an "electron.exe", I found that the system font library could not be obtained. Later, through Debug, I found that the "font.vbs" file could not be found.

**Comment by oldj** [comment]
I tested it under Windows 10 and it works. I use [electron-packager](https://github.com/electron-userland/electron-packager) for packaging.

**Comment by ZhkAff** [comment]
Thank you!
