### ISSUE TITLE
Angular Compatability

### ISSUE THREAD

**Issue by Rlcolli4** [oldj/node-font-list#10]
Good afternoon! I was wondering if you knew how compatible this package was in an Angular Application. I love the idea of how "getFonts" works, however it had issues loading in "child_process" and "fs". Once I followed some recommended fixes to get those working, I got "process is undefined" error when trying to run the function. Thanks in advance for any insights you can give me! Here are some details about what I am running locally with the package:
![localenviro](https://user-images.githubusercontent.com/12074293/73277568-9c8c3680-41a7-11ea-9351-7acb902f0627.PNG)

**Comment by oldj** [comment]
This package cannot be used in the browser environment. It depends on the Node.js environment and can be used in the server side or Electron.
