### ISSUE TITLE
electron 打包在windows下无法获取字体

### ISSUE THREAD

**Issue by awehook** [oldj/node-font-list#11]
您好，非常感谢。这里报告一个问题，electron 打包在windows下无法获取字体， 报错信息：
EPERM: operation not permitted, copyfile 'C:\Program Files\BlinkMind\resources\app.asar.unpacked\node_modules\font-list\libs\win32\fonts.vbs' -> 'C:\Users\zhou\AppData\Local\Temp\node-font-list-fonts.vbs'

**Comment by oldj** [comment]
我这儿没有遇到这个问题。看错误信息，似乎是将 fonts.vbs 复制到临时文件夹时没有权限？

**Comment by awehook** [comment]
感觉这个问题可能会在一部分用户的系统上存在，有没有办法不通过复制font.vbs到临时文件夹来执行这个vbs脚本，亦或者是通过调用windows api来实现获取字体

**Comment by oldj** [comment]
的确是个问题，我找找看有没有替代方案，你有什么好的方法也欢迎提出来。

**Comment by awehook** [comment]
好的

**Comment by oldj** [comment]
现在在 Windows 下会优先尝试使用 PowerShell 的方法来获取系统字体列表，这样就完全在命令中操作，不需要复制一个 vbs 文件了。你看看这个版本在你那儿有问题吗？

**Comment by awehook** [comment]
没有问题了。
