### ISSUE TITLE
中文字符出现乱码

### ISSUE THREAD

**Issue by vincentwan100** [oldj/node-font-list#13]
1. 请上 chcp 65001，代码如下：
powershell -command "chcp 65001;

**Comment by oldj** [comment]
能截个图吗？什么情况下出现的乱码？谢谢！

**Comment by vincentwan100** [comment]
Hi Oldj


辛苦了，我已经修改且提交，你这边审核通过一下，就可以了，这是参考文章：


1.&nbsp;https://blog.csdn.net/x356982611/article/details/80285930
2. 我修改的代码截图：

加上了这个代码：chcp 65001;
3. 之前本地读取字符乱码如下：

&nbsp;修改之后，就好了！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"oldj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月16日(星期四) 上午9:56
收件人:&nbsp;"oldj/node-font-list"<node-font-list@noreply.github.com&gt;;
抄送:&nbsp;"梓涵的爸爸 万勇"<909679623@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [oldj/node-font-list] 中文字符出现乱码 (#13)





 
能截个图吗？什么情况下出现的乱码？谢谢！

**Comment by vincentwan100** [comment]
217: ""Wingdings 2""
218: ""Wingdings 3""
219: ""Yu Gothic Light""
220: ""Yu Gothic Medium""
221: ""Yu Gothic UI Light""
222: ""Yu Gothic UI Semibold""
223: ""Yu Gothic UI Semilight""
224: ""Yu Gothic UI""
225: ""Yu Gothic""
226: "΢ܛ�����w"
227: ""΢ܛ�����w Light""
228: "΢���ź�"
229: ""΢���ź� Light""
230: "�¼����w-ExtB"
231: "��Բ"
232: "���Ĳ���"
233: "���ķ���"
234: "���Ŀ���"
235: "����"

我的环境是：window 10 + electron 4.2 + nodejs 10.16

**Comment by oldj** [comment]
好的，非常感谢！
我看到[你的修改](https://github.com/vincentwan100/node-font-list/commit/1b8dd3ab2116f1d30c8c5e79cafb40330f3b861d)了，你要不要提交一个 Pull request 到这个库来？或者我直接在这边修改？

**Comment by vincentwan100** [comment]
你这边直接修改就行了；谢谢

**Comment by oldj** [comment]
好的，已修改，再次感谢！
