### ISSUE TITLE
获取字体问题

### ISSUE THREAD

**Issue by MoeHero** [oldj/node-font-list#20]
现在获取的字体无法直接在css里面用
我改了一下 不知道是否可以提交pr

**Comment by oldj** [comment]
现在应该是可以直接在 CSS 里面用的，你发现了什么问题呢？

**Comment by MoeHero** [comment]
我对字体这块不太了解
不过一个字体可以有多个不同的粗细程度
如果一个字体有多个的话Drawing里面获取到的是更细分的字体 在css里不识别
比如有个字体是 汉仪正圆
它有2个粗细 75W和85W 现在你的这个会获取到 汉仪正圆-75W和汉仪正圆-85W
但是这样的CSS无法使用
需要 汉仪正圆 才可以

**Comment by MoeHero** [comment]
![image](https://user-images.githubusercontent.com/9930892/133983191-e01559ea-b518-4588-9e98-6b1a4f2804e1.png)

**Comment by oldj** [comment]
明白了，有一些边界情况可能我没有遇到，一直没有发现。
欢迎提交 PR。🙂

**Comment by oldj** [comment]
有一些边界情况可能我没有遇到，一直没有发现。

**Comment by MoeHero** [comment]
我改好了 不过我担心会不会影响以及在用的用户

**Comment by MoeHero** [comment]
就是css设置的实际上是FontFamily 而不是Font
应该这么理解emm

**Comment by MoeHero** [comment]
我提交一下你看一下吧

**Comment by MoeHero** [comment]
不过只改了windows下powershell的获取，vbs和其他环境没有修改

**Comment by oldj** [comment]
好的，谢谢，我看一下。

**Comment by oldj** [comment]
这个更新已经包含在 v1.4.0 了。
