### ISSUE TITLE
font-list not work in --asar electron packager

### ISSUE THREAD

**Issue by bilal-mo-saed** [oldj/node-font-list#4]
when build my electron project by
electron-packager . test --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/image/logo.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="test"

font-list not work but when remove --asar worked

show message 
error: Command failed: cscript "C:\Users\Your\release-builds\rc-win32-ia32\resources\app.asar\node_modules\font-list\libs\win32\fonts.vbs"
at ChildProcess.exithandler (child_process.js:304)
    at ChildProcess.emit (events.js:200)
    at maybeClose (internal/child_process.js:1021)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283)

**Comment by luiskugel** [comment]
I have the same problem. Does anyone have an idea how to fix this ?

**Comment by oldj** [comment]
On Windows systems, you need to extract the .vbs file from the asar package to a temporary directory, and then execute it, otherwise it will fail because the file cannot be found.
I will submit an update to deal with this issue later.

**Comment by oldj** [comment]
Try v1.2.1 or newer, it should work.
