### ISSUE TITLE
README

### ISSUE THREAD

**Issue by brettz9** [oldj/node-font-list#8]
Hi,

Thanks for clarifying on the README how the strings should appear in the array.

However, when nesting on RunKit, I see that even fonts with spaces do not have quotes around them:

https://runkit.com/brettz9/5dcdef88a792eb001acd7901

**Comment by oldj** [comment]
Thanks, this is a bug and has been fixed in v1.2.3.

**Comment by brettz9** [comment]
Thanks--and I appreciate your finding the source that had been missing.
