### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by brettz9** [oldj/node-font-list#9]
Hi,

The code at https://github.com/oldj/node-font-list/blob/master/libs/win32/index.js#L69-L71 is being flagged by https://lgtm.com/projects/g/oldj/node-font-list/?mode=list with an explanation for the concern at https://lgtm.com/rules/1510773276307/ . It appears that this concern could be minimized by using:

```js
let cmd = 'cscript'
execFile(cmd, [fn], (err, stdout, stderr) => {
```

Btw, I find LGTM.com to be a useful site which picks up issues like this which ESLint does not (and across multiple languages), and they have an integration for your site's PRs in case you might be interested: https://lgtm.com/help/lgtm/github-apps-integration

**Comment by oldj** [comment]
Thanks!
